<?php
$this->layout()->setLayout('empty');
?>
<!DOCTYPE html>
<html>
    <head>
        <title>myUnifiED Collaboration Infrastructure EngineBlock - Default Homepage</title>
    </head>
    <body>
        <h1>Welcome to myUnifiED Collaboration Infrastructure EngineBlock - Default Homepage!</h1>
        <p>
            If you see this message you've probably configured EngineBlock to not use any specialised routing. <br />
            To run an action go to: /modulename/controllername/actionname.
        </p>
    </body>
</html>
